#! /usr/bin/env ruby

excl = [
  "resources/collation",
  "resources/custom",
  "resources/locales",
  "resources/shared",
  "resources/unicode_data",
].map { |pattern| "grep -v #{pattern}" }

base_branch = ENV["BRANCH"] || "master"

files = `git diff --diff-filter=ACMRTUXB --name-only #{base_branch} . | #{excl.join(" | ")}`.split("\n")
`git diff #{base_branch} #{files.join(" ")} > /tmp/twitter-cldr-rb.diff`
`git diff --diff-filter=D #{base_branch} . >> /tmp/twitter-cldr-rb.diff`
exec "less /tmp/twitter-cldr-rb.diff"
